const lightNames = [
  "lifeBrazier_left",
  "lifeBrazier_middle",
  "lifeBrazier_right",
  "brazier_lefttop",
  "brazier_leftbottom",
  "brazier_righttop",
  "brazier_rightbottom",
  "brazier_bottomleft",
  "brazier_bottomright",
  "brazier_monkeysleft",
  "brazier_monkeysright",
  "game",
  "bumpkin",
  "npc",
  "brazier_backleft_level1",
  "brazier_backleft_level3",
  "brazier_backright_level1",
  "brazier_backright_level3",
  "brazier_frontleft_level1",
  "brazier_frontleft_level2",
  "brazier_frontright_level1",
  "brazier_frontright_level2",
] as const;

export type LightName = (typeof lightNames)[number];
